BE: Collapse migrations (#177)
ita-social-projects/dokazovi-be pull request #194
Opened 2021-03-03 16:58 UTC by invzbl3

develop

## GitHub Board

**Issue link**

[#11 Issue name ]( )

**Story link**

[#11 Story]( )

## Code reviewers
- [ ] @github_username

## Summary of issue

- [ ]  Summary of issue
- [ ]  Summary of issue

## Summary of change

- [ ]  Summary of change
- [ ]  Summary of change

2021-03-03 22:44 UTC, ad-artem-melnykov requested changes

2021-03-03 22:44 UTC, ad-artem-melnykov commented on src/main/resources/db/migration/V1__init_db.sql
> +	success boolean not null
Usually, the `Flyway` creates this table by itself. Looks like redundant

2021-03-03 22:44 UTC, ad-artem-melnykov commented on src/main/resources/db/migration/V1__init_db.sql
> +create table roles
Could you choose one SLQ convention for scripts? I prefer to use `UPPERCASE`.

2021-03-03 22:44 UTC, ad-artem-melnykov commented on src/main/resources/db/migration/V1__init_db.sql
>  );
Maybe would be better If you apply code format for all scripts? Does it make sense?

2021-03-03 22:54 UTC, ad-artem-melnykov commented
If you create a PR for merge in a dev/master branch, please fill all correspondent fields related to your PR.
For example:
Title: `PR - #### - Add some functionality` OR `Feature - #### - Add login page` etc.
Description: Leave short information about your PR and remove extras if needed

2021-03-05 08:25 UTC, melnikovae87 approved these changes

2021-03-05 16:30 UTC, merged