BE: Add field "videoUrl" and "previewImageUrl" to Post table
ita-social-projects/dokazovi-be pull request #206
Opened 2021-03-11 21:29 UTC by alexandr-bielan

develop

## GitHub Board

**Issue link**

[#11 Issue name ]( )

**Story link**

[#11 Story]( )

## Code reviewers
- [ ] @github_username

## Summary of issue

- [ ]  Summary of issue
- [ ]  Summary of issue

## Summary of change

- [ ]  Summary of change
- [ ]  Summary of change

2021-03-12 11:16 UTC, andrewtyshkovets commented on src/main/resources/db/migration/V1__init_db.sql
> +    ADD COLUMN VIDEO_URL VARCHAR,
@melnikovae87 Should we put default value "null" for this column? What's ur opinion?

2021-03-12 11:18 UTC, andrewtyshkovets commented on src/main/resources/db/migration/V1__init_db.sql
> +    ADD COLUMN VIDEO_URL VARCHAR,
If this field is optional for different typo of posts

2021-03-15 14:13 UTC, melnikovae87 requested changes

2021-03-15 14:13 UTC, melnikovae87 commented on src/main/java/com/softserveinc/dokazovi/entity/PostEntity.java
> +	@Column(columnDefinition = "TEXT", name = "preview_image_url")
Redundant

2021-03-15 14:13 UTC, melnikovae87 commented on src/main/java/com/softserveinc/dokazovi/entity/PostEntity.java
> +	@Column(columnDefinition = "TEXT", name = "video_url")
Redundant. Just remove `columnDefinition = "TEXT"`

2021-03-15 15:19 UTC, melnikovae87 approved these changes

2021-03-15 15:25 UTC, andrewtyshkovets approved these changes

2021-03-15 16:04 UTC, merged