Implement API for Post deleting #205
ita-social-projects/dokazovi-be pull request #225
Opened 2021-03-18 08:18 UTC by invzbl3

develop

## GitHub Board

**Issue link**

[#205](https://github.com/ita-social-projects/dokazovi-be/issues/205)

## Code reviewers
- [x] @melnikovae87

## Summary of issue

- [ ] Implement api endpoint controller for deleting posts.
- [ ] Implement service for deleting all priority posts.
- [ ] Implement repository for deleting all priority posts.
- [ ] Implement tests.

## Summary of change

- [ ] Implement API for Post deleting

2021-03-18 09:08 UTC, melnikovae87 requested changes

2021-03-18 09:08 UTC, melnikovae87 commented on src/main/java/com/softserveinc/dokazovi/controller/PostController.java
> +	@DeleteMapping(POST_DELETE_BY_ID)
Implicit endpoint. Finally it will look:
`localhost:8080/api` + `/post/` + `/{postId}` - _unclear what will do this endpoint_

2021-03-18 09:08 UTC, melnikovae87 commented on src/main/java/com/softserveinc/dokazovi/controller/PostController.java
> +	@DeleteMapping(POST_DELETE_BY_ID)
`localhost:8080/api` + `/post/` + `/{postId}` + `/delete' - hope will look better

2021-03-18 09:08 UTC, melnikovae87 commented on .idea/codeStyles/Project.xml
> -        <option name="TAB_SIZE" value="4" />
Why did you change this style?

2021-03-19 11:21 UTC, ad-artem-melnykov commented on src/main/java/com/softserveinc/dokazovi/controller/EndPoints.java
> +	public static final String POST_DELETE_BY_ID = "/{postId}/delete";
Sorry. Looks redundant. Please use the `DELETE` request with `/{postId}`.
Finally will be: `DELETE` request `localhost:8080/api/post/{postId}`

2021-03-19 12:09 UTC, ad-artem-melnykov commented on src/main/java/com/softserveinc/dokazovi/controller/EndPoints.java
> +	public static final String POST_DELETE_BY_ID = "/{postId}";
Just delete it. The `POST_GET_POST_BY_ID` and `POST_GET_POST_BY_ID` are equals

2021-03-22 13:03 UTC, melnikovae87 requested changes
Please consider my comments

2021-03-24 08:52 UTC, melnikovae87 approved these changes
Please check my comments and you can merge

2021-03-24 08:52 UTC, melnikovae87 commented on src/test/java/com/softserveinc/dokazovi/controller/PostControllerTest.java
>  	void archivePostById_WhenExists_isOk() throws Exception {
Looks like redundant

2021-03-24 08:52 UTC, melnikovae87 commented on src/test/java/com/softserveinc/dokazovi/controller/PostControllerTest.java
>  	void archivePostById_WhenNotExists_NotFound() throws Exception {
Looks like redundant

2021-03-24 13:22 UTC, merged