Create an endpoint for getting the Post Views Count
ita-social-projects/dokazovi-be pull request #343
Opened 2021-06-08 23:49 UTC by alexandr-bielan

develop

## GitHub Board

**Issue link**

[#316  Issue name ](https://github.com/ita-social-projects/dokazovi-be/issues/316 )
  
## Code reviewers
- [ ] @teaFunny

## Summary of issue

- [ ]   Implement an API endpoint controller for getting the Post Views Count
- [ ]    Implement a service for getting the Post Views Count
- [ ]    Implement a GoogleAnalytics Class for getting the Post Views Count
  
## Summary of change

- [ ]  Implemented an API endpoint controller for getting the Post Views Count
 - [ ] Implemented a service for getting the Post Views Count
 - [ ] Implemented a GoogleAnalytics Class for getting the Post Views Count

2021-06-10 09:20 UTC, teaFunny requested changes

2021-06-10 09:20 UTC, teaFunny commented on src/main/java/com/softserveinc/dokazovi/analytics/GoogleAnalytics.java
> +		} catch (GeneralSecurityException e) {
You can add e to the logger as first argument

2021-06-10 09:20 UTC, teaFunny commented on src/main/resources/client_secrets.json
> +{
Could you remove the private key, id, client mail, id from git and set it on the server only?

2021-06-12 19:39 UTC, lizozavr approved these changes

2021-06-12 19:42 UTC, merged