filter by modified_at added + getFakeViews bug fixed
ita-social-projects/dokazovi-be pull request #486
Opened 2021-11-15 11:03 UTC by mvalchyshen

develop

## GitHub Board

**Issue link**

[#481Admin filter all materials by “Дата зміни статусу ]( )

**Story link**

[#376 Admin filter all materials by “Дата зміни статусу”]( )

## Code reviewers
- [ ] @teaFunny 

## Summary of issue

- [ ] Add Date datatype to existing method

## Summary of change

- [ ]  add Date to PostController,PostService,PostRepository
- [ ]  Bug fixed in getFakeViews method

2021-11-15 11:24 UTC, teaFunny requested changes

2021-11-15 11:24 UTC, teaFunny commented on src/main/java/com/softserveinc/dokazovi/service/impl/PostServiceImpl.java
> +		if (!date.isEmpty()) {
Please refactor duplicated code.

2021-11-15 21:39 UTC, mvalchyshen commented on src/main/java/com/softserveinc/dokazovi/service/impl/PostServiceImpl.java
> +		if (!date.isEmpty()) {
done

2021-11-23 10:48 UTC, teaFunny approved these changes

2021-11-23 11:53 UTC, merged