Feature/doctor-preview-test
ita-social-projects/dokazovi-be pull request #51
Opened 2020-11-15 08:07 UTC by AntonMishyn

develop

## GitHub Board

**Issue link**

[#34 BE - doctors preview task (main page) ](https://github.com/ita-social-projects/dokazovi-be/issues/34)

**Story link**

[#13 Story](https://github.com/ita-social-projects/dokazovi-be/issues/13)

## Code reviewers
- [x] @melnikovae87

## Summary of issue

1. - [x] DTO for doctor (and latest post from him)
2. - [x] API (POST) controller with request configuration
3. - [x] Service layer
4. - [x] Repository layer (sort by making posts)
5. - [x] Unit tests

## Summary of change

- [x]  Refactor Entities
- [x]  Implement UnitTests for UserController, mappers, UserService.

2020-11-15 09:19 UTC, ponruslan requested changes

2020-11-15 09:19 UTC, ponruslan commented on src/main/java/com/softserveinc/dokazovi/entity/DirectionEntity.java
> +	private Set<PostEntity> mainPostsDirections = new HashSet<>();
do not initialize fields in entity

2020-11-15 09:19 UTC, ponruslan commented on src/main/java/com/softserveinc/dokazovi/entity/DirectionEntity.java
> +	private Set<PostEntity> posts = new HashSet<>();
do not initialize fields in entity

2020-11-15 09:19 UTC, ponruslan commented on src/main/java/com/softserveinc/dokazovi/entity/DirectionEntity.java
> +	private Set<UserEntity> mainUsersDirections = new HashSet<>();
do not initialize fields in entity

2020-11-15 09:19 UTC, ponruslan commented on src/main/java/com/softserveinc/dokazovi/entity/DirectionEntity.java
> +	private Set<UserEntity> users = new HashSet<>();
do not initialize fields in entity

2020-11-15 09:19 UTC, ponruslan commented on src/main/java/com/softserveinc/dokazovi/entity/InstitutionEntity.java
> +	private Set<UserEntity> mainUsersInstitution = new HashSet<>();
do not initialize fields in entity

2020-11-15 09:19 UTC, ponruslan commented on src/main/java/com/softserveinc/dokazovi/entity/InstitutionEntity.java
> +	private Set<UserEntity> users = new HashSet<>();
do not initialize fields in entity

2020-11-15 09:19 UTC, ponruslan commented on src/main/java/com/softserveinc/dokazovi/entity/PostEntity.java
> +	private Set<DirectionEntity> directions = new HashSet<>();
do not initialize fields in entity

2020-11-15 09:19 UTC, ponruslan commented on src/main/java/com/softserveinc/dokazovi/entity/PostEntity.java
> +	private Set<TagEntity> tags = new HashSet<>();
do not initialize fields in entity

2020-11-15 09:19 UTC, ponruslan commented on src/main/java/com/softserveinc/dokazovi/entity/PostEntity.java
> +	private Set<SourceEntity> sources = new HashSet<>();
do not initialize fields in entity

2020-11-15 09:19 UTC, ponruslan commented on src/main/java/com/softserveinc/dokazovi/entity/PostTypeEntity.java
> +	private Set<PostEntity> posts = new HashSet<>();
do not initialize fields in entity

2020-11-15 09:19 UTC, ponruslan commented on src/main/java/com/softserveinc/dokazovi/entity/RegionEntity.java
> +	private Set<CityEntity> cities = new HashSet<>();
do not initialize fields in entity

2020-11-15 09:19 UTC, ponruslan commented on src/main/java/com/softserveinc/dokazovi/entity/RoleEntity.java
>  	private Set<UserEntity> users = new HashSet<>();
do not initialize fields in entity

2020-11-15 09:19 UTC, ponruslan commented on src/main/java/com/softserveinc/dokazovi/entity/SourceEntity.java
> +	private Set<PostEntity> posts = new HashSet<>();
do not initialize fields in entity

2020-11-15 09:19 UTC, ponruslan commented on src/main/java/com/softserveinc/dokazovi/entity/UserEntity.java
> +	private Set<PostEntity> posts = new HashSet<>();
do not initialize fields in entity

2020-11-15 09:19 UTC, ponruslan commented on src/main/java/com/softserveinc/dokazovi/entity/UserEntity.java
> +	private Set<CharityEntity> charities = new HashSet<>();
do not initialize fields in entity

2020-11-15 09:19 UTC, ponruslan commented on src/main/java/com/softserveinc/dokazovi/entity/UserEntity.java
> +	private Set<InstitutionEntity> institutions = new HashSet<>();
do not initialize fields in entity

2020-11-15 09:19 UTC, ponruslan commented on src/main/java/com/softserveinc/dokazovi/entity/UserEntity.java
> +	private Set<RoleEntity> roles = new HashSet<>();
do not initialize fields in entity

2020-11-15 09:19 UTC, ponruslan commented on src/main/java/com/softserveinc/dokazovi/entity/UserEntity.java
> +	private Set<DirectionEntity> directions = new HashSet<>();
do not initialize fields in entity

2020-11-15 09:19 UTC, ponruslan commented on src/main/java/com/softserveinc/dokazovi/entity/UserEntity.java
> +	private Set<SourceEntity> sources = new HashSet<>();
do not initialize fields in entity

2020-11-15 09:19 UTC, ponruslan commented on src/test/java/com/softserveinc/dokazovi/mapper/UserMapperTest.java
> +		userEntity.getPosts().add(postEntity);
use userEntity.setPosts(Set.of(postEntity, latestPostEntity)).

2020-11-15 11:44 UTC, ponruslan approved these changes

2020-11-16 07:48 UTC, melnikovae87 approved these changes

2020-11-16 07:50 UTC, merged