Refresh token logic
ita-social-projects/dokazovi-be pull request #550
Opened 2022-07-20 15:29 UTC by fortamt

develop

## GitHub Board

**Issue link**

[Refresh Token logic #549](https://github.com/ita-social-projects/dokazovi-be/issues/549 )

**Story link**

[-](- )

## Code reviewers
- [ ] @teaFunny 

## Summary of issue

- [ ]  create /refreshtoken endpoint
- [ ] add refresh token logic

## Summary of change

- [ ]  created /refreshtoken endpoint
- [ ]  added refresh token repository
- [ ] added table for refresh tokens(flyway migrations)
- [ ] added RefreshTokenService.class
- [ ] added Tests for all
- [ ] added links for enviroment variables

2022-08-03 17:21 UTC, V-Kaidash requested changes

2022-08-03 17:21 UTC, V-Kaidash commented on src/main/java/com/softserveinc/dokazovi/security/RefreshTokenService.java
> +		refreshToken = refreshTokenRepository.save(refreshToken);
Does something changes after 
`refreshTokenRepository.save(refreshToken);`
Why are you reassigning refreshToken variable?

2022-08-03 17:21 UTC, V-Kaidash commented on src/main/java/com/softserveinc/dokazovi/security/RefreshTokenService.java
> +
Please remove empty lines

2022-08-03 17:21 UTC, V-Kaidash commented on src/main/java/com/softserveinc/dokazovi/security/TokenProvider.java
> +
Please remove empty lines

2022-08-03 17:21 UTC, V-Kaidash commented on src/main/resources/application.properties
> +app.auth.refreshTokenExpirationMsec= ${REFRESH_TOKEN_EXPIRATION_MSEC}
What happened if these two parameters not set?
Does it make sense to set some default values?

2022-08-03 17:21 UTC, V-Kaidash commented on src/main/java/com/softserveinc/dokazovi/config/AppProperties.java
> +	public static class Auth {
Please check your IDE settings for indentation and tabs and adjust your code accordingly. Also check other files you have edited. IDE settings should be something like this 
![image](https://user-images.githubusercontent.com/86650723/182669668-061d3ea1-8c76-4571-9508-9cb53c85362c.png)

2022-08-03 17:21 UTC, V-Kaidash commented on src/test/java/com/softserveinc/dokazovi/security/RefreshTokenServiceTest.java
> +
Please remove empty lines & fix indentation (see IDE settings above)

2022-08-07 18:36 UTC, V-Kaidash approved these changes
Refresh token proof/demo
https://drive.google.com/file/d/1KBhr29pPqhQ5N0Asw3RhYo1kZlmL02fS/view?usp=sharing

All looks good for me.
Let's wait on the final review from Alina before merging.

2022-08-09 07:50 UTC, teaFunny approved these changes

2022-08-09 09:58 UTC, merged