Fixed return of findAllExperts to correct sorting repository
ita-social-projects/dokazovi-be pull request #553
Opened 2022-07-27 12:28 UTC by IlyaKosarenko

Fixed return of findAllExperts to correct sorting repository if there are no regions, directions and username + fixed tests in UserServiceImplTest

develop

User story and test case links:
Bug report: https://github.com/ita-social-projects/dokazovi-requirements/issues/562
Test case: https://github.com/ita-social-projects/dokazovi-requirements/issues/441
User story: https://github.com/ita-social-projects/dokazovi-requirements/issues/301

2022-08-04 17:47 UTC, V-Kaidash reviewed
All seems ok to me.
Could you please add swagger data Before/After changes?

2022-08-06 14:53 UTC, IlyaKosarenko commented
Before:
![image](https://user-images.githubusercontent.com/95490405/183254245-23ceab12-f8b1-4197-9b80-7f01ffb03641.png)

After:
![image](https://user-images.githubusercontent.com/95490405/183254197-424f65ba-da1e-477c-bebe-2524e8f561c5.png)

2022-08-07 21:09 UTC, V-Kaidash requested changes
1. When I asked for swagger data, I meant json file you can download here 
![image](https://user-images.githubusercontent.com/86650723/183310734-e844d2d1-a2b9-46ad-991b-784d842b7a8a.png)

2. On your BEFORE screenshot, we can see error result, but if you check actual result on mobile version - it returns some data. Hence, you might be addressing the wrong endpoint or method in your solution. Could you please check what is the correct endpoint or method should be?
![image](https://user-images.githubusercontent.com/86650723/183310851-8757115e-b097-469e-9ddb-1e7444292480.png)

3. The endpoint and method you tried to fix in the current commit revealed an error that might not be related to the described bug.  If so, please add a separate issue for investigation.

2022-08-31 14:53 UTC, V-Kaidash approved these changes

2022-08-31 15:09 UTC, merged